#ifndef ERROR_CODES_HPP
# define ERROR_CODES_HPP

#define HTTP_OK "200"
#define HTTP_BAD_REQUEST "400"
#define HTTP_NOT_FOUND "404"
#define HTTP_METHOD_NOT_ALLOWED "405"
#define HTTP_INTERNAL_SERVER_ERROR "500"
#define HTTP_SERVICE_UNAVAILABLE "503"

#endif